Repository Netcracker/KubeMarine, pull requests merged in 2022-12, with the labels that each got.

#253 Apparmor check_paas
  documentation/Kubecheck.md
  kubemarine/apparmor.py
  kubemarine/procedures/check_paas.py
  kubemarine/system.py
Labels: improvement

#305 [Hot fix]Build and check binary files
  Dockerfile
  requirements.txt
Labels: bug

#303 [MANOPD-81950] - fix help sections
  kubemarine/core/flow.py
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/do.py
Labels: improvement

#300 [MANOPD-82181] - support string plugin.install values
  kubemarine/core/utils.py
  kubemarine/plugins/__init__.py
  kubemarine/plugins/calico.py
  kubemarine/plugins/nginx_ingress.py
  kubemarine/procedures/check_paas.py
Labels: bug

#308 The AppArmor check fails
  kubemarine/procedures/check_paas.py
Labels: bug

#311 Update document use binary files and remove support build windows binary
  .github/workflows/release.yaml
  README.md
Labels: documentation

#312 [PSUPCLPL-11209] Added issue to Troubleshooting.md
  documentation/Troubleshooting.md
Labels: documentation

#314 [MANOPD-82463] Kubemarine --version for binary doesn't work
  kubemarine/__main__.py
Labels: feature

#301 [MANOPD-82359] Calico toleration fix
  documentation/Installation.md
  kubemarine/plugins/calico.py
  kubemarine/templates/plugins/calico-v3.22.yaml.j2
  kubemarine/templates/plugins/calico-v3.24.yaml.j2
Labels: bug

#310 [MANOPD-82386] - add task list in help section
  kubemarine/core/flow.py
  kubemarine/procedures/add_node.py
  kubemarine/procedures/backup.py
  kubemarine/procedures/cert_renew.py
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/install.py
  kubemarine/procedures/manage_psp.py
  kubemarine/procedures/manage_pss.py
  kubemarine/procedures/migrate_cri.py
  kubemarine/procedures/reboot.py
  kubemarine/procedures/remove_node.py
  kubemarine/procedures/restore.py
  kubemarine/procedures/upgrade.py
Labels: improvement

#319 [PSUPCLPL-11062] Update defaults.yaml
  kubemarine/resources/configurations/defaults.yaml
Labels: bug

#315 [MANOPD-82392] - add check_iaas tasks for check pakages and repos
  documentation/Kubecheck.md
  kubemarine/apt.py
  kubemarine/packages.py
  kubemarine/procedures/check_iaas.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/scripts/check_url_availability.py
  kubemarine/system.py
  kubemarine/yum.py
Labels: improvement

#297 [MANOPD-81952] - use internal address if address is not defined
  README.md
  kubemarine/procedures/remove_node.py
  kubemarine/system.py
  test/unit/test_inventory.py
Labels: improvement

#322 [MANOPD-82072] fix containerd version
  kubemarine/resources/configurations/globals.yaml
Labels: bug

#324 [PSUPCLPL-11062] Update Troubleshooting.md
  documentation/Troubleshooting.md
Labels: documentation
