Repository Netcracker/KubeMarine, pull requests merged in 2022-09, with the labels that each got.

#225 [PSUPCLPL-10728]Error: MountVolume.SetUp failed for volume "kube-api-access-gd628" object kube-root-ca.crt not registered
  kubemarine/resources/configurations/globals.yaml
Labels: bug, feature

#226 [PSUPCLPL-10685] Calico CNI panicked during ADD: runtime error: invalid memory address or nil pointer dereference
  kubemarine/resources/configurations/globals.yaml
  kubemarine/templates/plugins/calico-v3.24.yaml.j2
Labels: feature

#228 [MANOPD-79810] calico environment variables forwarding support
  documentation/Installation.md
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/templates/plugins/calico-v3.21.yaml.j2
  kubemarine/templates/plugins/calico-v3.22.yaml.j2
  kubemarine/templates/plugins/calico-v3.24.yaml.j2
Labels: improvement

#229 [MANOPD-1] Update Installation.md and sha sum kubelet
  documentation/Installation.md
  kubemarine/resources/configurations/globals.yaml
Labels: bug, documentation

#232 MANOPD-78236 Fixed patch autodeletion workflow
  .github/workflows/patch.yaml
  .github/workflows/tests.yaml
Labels: bug
