Repository Netcracker/KubeMarine, pull requests merged in 2022-10, with the labels that each got.

#243 Fix calico paas check
  kubemarine/procedures/check_paas.py
  kubemarine/resources/configurations/defaults.yaml
Labels: bug

#233 MANOPD-76951 Fix "remote_node" procedure for miniHA
  kubemarine/core/cluster.py
  kubemarine/core/utils.py
Labels: bug

#234 Update Installation.md
  documentation/Installation.md
Labels: documentation

#239 [MANOPD-80329] Do not remove default sections from finalized inventory
  kubemarine/core/defaults.py
Labels: bug

#242 MANOPD-80314 Support public helm charts
  kubemarine/plugins/__init__.py
Labels: bug

#254 Add ability to specify custom Helm release name
  documentation/Installation.md
  kubemarine/plugins/__init__.py
Labels: documentation, feature

#251 Update Installation.md , adding information about Kubernetes 1.24.2 to table.
  documentation/Installation.md
Labels: documentation

#246 [MANOPD-80122] check_paas DR clusters connectivity checks
  documentation/Kubecheck.md
  kubemarine/core/flow.py
  kubemarine/procedures/check_paas.py
Labels: improvement

#264 [MANOPD-80122] geo-check better ui
  kubemarine/procedures/check_paas.py
Labels: bug

#258 [MANOPD-80822] change default typha settings
  kubemarine/resources/configurations/defaults.yaml
Labels: improvement

#260 MANOPD-80882 Threads share the same gateway connection instance
  kubemarine/core/connections.py
Labels: bug

#268 [MANOPD-80822] change default typha settings
  kubemarine/jinja.py
  kubemarine/templates/plugins/calico-v3.21.yaml.j2
  kubemarine/templates/plugins/calico-v3.22.yaml.j2
  kubemarine/templates/plugins/calico-v3.24.yaml.j2
Labels: improvement

#265 MANOPD-78395 Haproxy maintenance mode improvements
  documentation/Installation.md
  kubemarine/core/cluster.py
  kubemarine/core/defaults.py
  kubemarine/core/resources.py
  kubemarine/demo.py
  kubemarine/haproxy.py
  kubemarine/patches/__init__.py
  kubemarine/patches/p1_migrate_not_bind_vrrp.py
  kubemarine/patches/p2_haproxy_maintenance_listen_internal.py
  kubemarine/procedures/check_paas.py
  kubemarine/templates/haproxy_mntc.cfg.j2
  test/unit/test_defaults.py
  test/unit/test_haproxy.py
Labels: bug, documentation, feature
