Repository Netcracker/KubeMarine, pull requests merged in 2022-11, with the labels that each got.

#252 Ubuntu LTS 22.04.1 support
  documentation/Installation.md
  kubemarine/procedures/add_node.py
  kubemarine/procedures/check_iaas.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/configurations/globals.yaml
  kubemarine/templates/haproxy.cfg.j2
Labels: feature

#240 Timeout for thirdparty download
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/thirdparties.py
Labels: improvement, assessed

#271 rollback note
  documentation/Maintenance.md
Labels: documentation

#263 [MANOPD-80626] Kubernetes v1.25 adoption
  documentation/Maintenance.md
  kubemarine/admission.py
  kubemarine/kubernetes/__init__.py
  kubemarine/patches/__init__.py
  kubemarine/patches/p1_upgrade_crictl_version.py
  kubemarine/patches/p2_upgrade_calico_version.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/configurations/globals.yaml
  kubemarine/templates/plugins/dashboard-v2.7.yaml.j2
  kubemarine/templates/plugins/nginx-ingress-controller-v1.4.yaml.j2
Labels: feature

#255 Doc/kubmarine install via docker
  README.md
  documentation/internal/Kubemarine-docker-building.md
Labels: documentation

#283 [MANOPD-80822] adjust typha toleration settings and add toleration configuration option
  documentation/Installation.md
  kubemarine/templates/plugins/calico-v3.21.yaml.j2
  kubemarine/templates/plugins/calico-v3.22.yaml.j2
  kubemarine/templates/plugins/calico-v3.24.yaml.j2
Labels: feature

#285 [MANOPD-81657] Revert "Bump ansible from 2.9.9 to 4.2.0"
  requirements.txt
  setup.cfg
Labels: bug

#281 [MANOPD-80808]Failed CIS compliance checks for Kubernetes v1.23 deployed from Kubemarine 0.7.0
  kubemarine/kubernetes/__init__.py
  kubemarine/resources/configurations/defaults.yaml
Labels: improvement, feature

#279 [MANOPD-81448] Calico update automation
  kubemarine/plugins/calico.py
  kubemarine/plugins/yaml/calico-v3.22.2.yaml.original
  kubemarine/plugins/yaml/calico-v3.24.1.yaml.original
  kubemarine/plugins/yaml/calico-v3.24.2.yaml.original
  kubemarine/resources/configurations/defaults.yaml
Labels: improvement

#290 [MANOPD-81799]Deploy Kubernetes failed
  kubemarine/plugins/calico.py
Labels: bug

#291 [MANOPD-81799] Fix images
  kubemarine/plugins/calico.py
  kubemarine/resources/configurations/defaults.yaml
Labels: bug

#293 [MANOPD-81799] Absolute path
  kubemarine/plugins/calico.py
  kubemarine/resources/configurations/defaults.yaml
Labels: bug

#294 Kubernetes 1.25 pause version fix
  kubemarine/resources/configurations/globals.yaml
Labels: bug

#278 MANOPD-81038 MANOPD-78302 Refactoring and fixes of OS/package versions
  documentation/Installation.md
  kubemarine/apparmor.py
  kubemarine/audit.py
  kubemarine/core/cluster.py
  kubemarine/core/defaults.py
  kubemarine/core/group.py
  kubemarine/core/resources.py
  kubemarine/core/utils.py
  kubemarine/cri/__init__.py
  kubemarine/cri/containerd.py
  kubemarine/cri/docker.py
  kubemarine/demo.py
  kubemarine/haproxy.py
  kubemarine/keepalived.py
  kubemarine/kubernetes/__init__.py
  kubemarine/packages.py
  kubemarine/procedures/add_node.py
  kubemarine/procedures/backup.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/install.py
  kubemarine/procedures/migrate_cri.py
  kubemarine/procedures/upgrade.py
  kubemarine/selinux.py
  kubemarine/system.py
  test/unit/core/test_cluster.py
  test/unit/core/test_flow.py
  test/unit/core/test_run_actions.py
  test/unit/test_audit.py
  test/unit/test_haproxy.py
  test/unit/test_keepalived.py
  test/unit/test_migrate_cri.py
  test/unit/test_packages.py
  test/unit/test_upgrade.py
Labels: bug, documentation, improvement

#289 MANOPD-81791 README improvements
  README.md
Labels: documentation
