Repository Netcracker/KubeMarine, pull requests merged in 2023-08, with the labels that each got.

#479 [PSUPCLPL-12898] Enabling proxy protocol for ingress-nginx and HAProxy
  documentation/Installation.md
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/templates/haproxy.cfg.j2
  test/unit/plugins/test_nginx_ingress.py
Labels: improvement

#475 patch for kubeadm_flags
  kubemarine/patches/__init__.py
  kubemarine/patches/p1_kubeadm_flags.py
Labels: improvement

#484 Refactoring Check Paas, Check IaaS tests
  kubemarine/__main__.py
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/check_paas.py
Labels: improvement, feature

#480 [PSUPCLPL-13194] Restore calicoctl executable
  kubemarine/core/group.py
  kubemarine/procedures/check_paas.py
  kubemarine/thirdparties.py
Labels: bug

#478 MANOPD-90998 Complete type annotations of all Kubemarine modules
  kubemarine/__main__.py
  kubemarine/admission.py
  kubemarine/core/cluster.py
  kubemarine/core/defaults.py
  kubemarine/core/flow.py
  kubemarine/core/log.py
  kubemarine/core/resources.py
  kubemarine/core/utils.py
  kubemarine/coredns.py
  kubemarine/demo.py
  kubemarine/kubernetes/__init__.py
  kubemarine/kubernetes/object.py
  kubemarine/packages.py
  kubemarine/patches/p1_kubeadm_flags.py
  kubemarine/plugins/__init__.py
  kubemarine/procedures/add_node.py
  kubemarine/procedures/backup.py
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/do.py
  kubemarine/procedures/install.py
  kubemarine/procedures/migrate_cri.py
  kubemarine/procedures/migrate_kubemarine.py
  kubemarine/procedures/remove_node.py
  kubemarine/procedures/restore.py
  kubemarine/procedures/upgrade.py
  kubemarine/testsuite.py
  pyproject.toml
  test/unit/core/test_flow.py
Labels: improvement

#350 Remove --ignore-schema-errors CLI option
  kubemarine/core/flow.py
  kubemarine/core/schema.py
  kubemarine/procedures/do.py
Labels: improvement

#486 [PSUPCLPL-13204] Add Etcd Corruption case to TG
  documentation/Troubleshooting.md
Labels: documentation

#489 CPDEV-91439 Work around broken pip installation on GitHub macos11 VM
  .github/workflows/ci.yaml
Labels: bug

#490 CPDEV-91458 Add examples how to write patches
  documentation/internal/Patches.md
  kubemarine/core/flow.py
  kubemarine/procedures/install.py
Labels: documentation

#487 PSUPCLPL-13194 Optimize downloading of Kubernetes resources during backup
  kubemarine/core/cluster.py
  kubemarine/core/connections.py
  kubemarine/core/executor.py
  kubemarine/core/group.py
  kubemarine/core/resources.py
  kubemarine/core/utils.py
  kubemarine/demo.py
  kubemarine/procedures/backup.py
  kubemarine/resources/configurations/globals.yaml
  test/unit/test_backup.py
Labels: improvement

#488 [CPDEV-91425] - Remove podman requirement
  documentation/Installation.md
  documentation/Maintenance.md
  examples/cluster.yaml/allinone-cluster-ol7.yaml
  kubemarine/cri/__init__.py
  kubemarine/cri/containerd.py
  kubemarine/packages.py
  kubemarine/patches/__init__.py
  kubemarine/patches/p1_replace_podman_to_ctr.py
  kubemarine/patches/software_upgrade.yaml
  kubemarine/procedures/migrate_kubemarine.py
  kubemarine/procedures/restore.py
  kubemarine/procedures/upgrade.py
  kubemarine/resources/configurations/compatibility/internal/packages.yaml
  kubemarine/resources/configurations/globals.yaml
  kubemarine/resources/etalons/patches/software_upgrade.yaml
  kubemarine/resources/scripts/etcdctl.sh
  scripts/thirdparties/src/software/packages.py
  test/unit/test_migrate_kubemarine.py
  test/unit/test_packages.py
  test/unit/test_upgrade.py
  test/unit/tools/thirdparties/test_sync.py
Labels: improvement

#493 [CPDEV-89888] Support for plugins resources requests/limits
  documentation/Installation.md
  kubemarine/core/defaults.py
  kubemarine/patches/__init__.py
  kubemarine/patches/p2_inventory_plugins_resources.py
  kubemarine/plugins/calico.py
  kubemarine/plugins/kubernetes_dashboard.py
  kubemarine/plugins/local_path_provisioner.py
  kubemarine/plugins/manifest.py
  kubemarine/plugins/nginx_ingress.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/definitions/plugins/calico.json
  kubemarine/resources/schemas/definitions/plugins/generic_plugin.json
  kubemarine/resources/schemas/definitions/plugins/kubernetes-dashboard.json
  kubemarine/resources/schemas/definitions/plugins/local-path-provisioner.json
  kubemarine/resources/schemas/definitions/plugins/nginx-ingress-controller.json
Labels: documentation, improvement

#492 [CPDEV-91579] Stream helm output to logging framework
  kubemarine/plugins/__init__.py
Labels: improvement

#491 [CPDEV-91452] k8s v1.28.0 support and 3rdparty update
  .github/workflows/integration_tests.yaml
  documentation/Installation.md
  kubemarine/admission.py
  kubemarine/kubernetes/__init__.py
  kubemarine/patches/software_upgrade.yaml
  kubemarine/plugins/yaml/calico-v3.26.1-original.yaml
  kubemarine/plugins/yaml/nginx-ingress-controller-v1.8.1-original.yaml
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/install.py
  kubemarine/procedures/migrate_cri.py
  kubemarine/resources/configurations/compatibility/internal/kubernetes_images.yaml
  kubemarine/resources/configurations/compatibility/internal/packages.yaml
  kubemarine/resources/configurations/compatibility/internal/plugins.yaml
  kubemarine/resources/configurations/compatibility/internal/thirdparties.yaml
  kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml
  kubemarine/resources/configurations/defaults.yaml
  test/unit/plugins/test_calico.py
  test/unit/test_upgrade.py
Labels: improvement

#497 [CPDEV-91748][CPDEV-91752] Fix procedure install and delete PSS for Kubernetes v1.28
  kubemarine/admission.py
Labels: bug, improvement

#495 [CPDEV-91646] Fixes and improvements of Kubernetes audit policy maintenance
  documentation/Installation.md
  documentation/Kubecheck.md
  kubemarine/kubernetes/__init__.py
  kubemarine/patches/__init__.py
  kubemarine/patches/p4_reconfigure_audit_policy.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/install.py
  kubemarine/procedures/upgrade.py
Labels: bug, documentation, improvement

#499 [CPDEV-91618] update public registry in documentation
  documentation/Installation.md
  documentation/Maintenance.md
  documentation/Troubleshooting.md
  examples/cluster.yaml/full-cluster.yaml
  examples/procedure.yaml/full-restore.yaml
Labels: documentation

#501 Add proxy protocol issue in troubleshooting guide
  .github/workflows/integration_tests.yaml
  ci/default_cluster.yaml
  ci/extended_cluster.yaml
  documentation/Troubleshooting.md
Labels: bug, documentation
