Repository Netcracker/KubeMarine, pull requests merged in 2023-07, with the labels that each got.

#467 Restore fix #457
  kubemarine/plugins/__init__.py
Labels: duplicate

#466 [MANOPD-90298] add "serializeImagePulls: false" by default to kubelet config
  documentation/Installation.md
  kubemarine/resources/configurations/defaults.yaml
Labels: improvement

#469 [MANOPD-88960] Remove PSP from defaults for Kubernetes higher than 1.24 version
  kubemarine/admission.py
Labels: bug

#453 [MANOPD-88293] Update kubeadm-flags.env after successful upgrade of k8s version
  kubemarine/kubernetes/__init__.py
  kubemarine/procedures/migrate_cri.py
  kubemarine/procedures/upgrade.py
Labels: improvement

#471 [MANOPD-90205] fix for vulnerability scanning failures
  kubemarine/kubernetes/__init__.py
Labels: improvement

#468 [MANOPD-90366] Improvements in remote executor and logging
  kubemarine/__main__.py
  kubemarine/apt.py
  kubemarine/audit.py
  kubemarine/core/cluster.py
  kubemarine/core/connections.py
  kubemarine/core/environment.py
  kubemarine/core/errors.py
  kubemarine/core/executor.py
  kubemarine/core/group.py
  kubemarine/core/log.py
  kubemarine/core/utils.py
  kubemarine/core/yaml_merger.py
  kubemarine/cri/containerd.py
  kubemarine/cri/docker.py
  kubemarine/demo.py
  kubemarine/haproxy.py
  kubemarine/kubernetes/__init__.py
  kubemarine/packages.py
  kubemarine/plugins/__init__.py
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/install.py
  kubemarine/procedures/upgrade.py
  kubemarine/system.py
  kubemarine/testsuite.py
  kubemarine/yum.py
  test/unit/core/test_executor.py
  test/unit/core/test_group.py
  test/unit/test_audit.py
  test/unit/test_group.py
  test/unit/test_workaround.py
  test/unit/utils.py
Labels: bug, improvement

#470 [MANOPD-89259] Use_ssh_password_instead_of_ssh_key_in_k8s_installation
  README.md
  documentation/Installation.md
  examples/cluster.yaml/allinone-cluster-ol7.yaml
  examples/cluster.yaml/allinone-cluster.yaml
  examples/cluster.yaml/full-cluster.yaml
  examples/cluster.yaml/miniha-cluster.yaml
  examples/cluster.yaml/minimal-cluster.yaml
  examples/cluster.yaml/typical-cluster.yaml
  kubemarine/core/connections.py
  kubemarine/core/utils.py
  kubemarine/resources/schemas/definitions/gateway_node.json
  kubemarine/resources/schemas/definitions/node_defaults.json
Labels: feature

#477 [MANOPD-88960] Remove PSP from defaults for Kubernetes higher than 1.24 version
  kubemarine/admission.py
Labels: bug
