Repository Netcracker/KubeMarine, pull requests merged in 2023-03, with the labels that each got.

#359 [PSUPCLPL-11755] Update TG: add No Pod-to-Pod Traffic for Some Nodes
  documentation/Troubleshooting.md
Labels: documentation

#360 Fix calico configuration check
  kubemarine/procedures/check_paas.py
Labels: bug

#369 MANOPD-84442 Fix Blowfish deprecation warning
  pyproject.toml
Labels: bug

#370 [MANOPD-85375] CentOS kernel and Calico compatibility
  documentation/Installation.md
Labels: documentation

#349 Fix resolution of exponential float by PyYAML
  kubemarine/__main__.py
  test/unit/test_keepalived.py
Labels: bug

#366 Fix replacement of package README links
  pyproject.toml
  setup.py
Labels: bug

#367 [PSUPCLPL-11680] adjust plugins and nodes timeouts
  documentation/Installation.md
  kubemarine/core/group.py
  kubemarine/kubernetes/__init__.py
  kubemarine/plugins/__init__.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/configurations/globals.yaml
  kubemarine/resources/schemas/cluster.json
  kubemarine/resources/schemas/definitions/globals.json
Labels: documentation, improvement

#371 [PSUPCLPL-11899] kubemarine/kubernetes/__init__.py
  kubemarine/kubernetes/__init__.py
Labels: improvement

#380 increase deployments.expect.retries
  kubemarine/resources/configurations/globals.yaml
Labels: bug

#378 PSUPCLPL-11968 support latest k8s: 1.23,1.24,1.25
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/configurations/globals.yaml
  kubemarine/resources/schemas/definitions/services/kubeadm.json
  test/unit/test_upgrade.py
Labels: improvement

#377 [PDSDNREQ-7070] HAproxy running with Root, should move to non-root
  kubemarine/patches/__init__.py
  kubemarine/patches/p2_fix_haproxy_user.py
  kubemarine/templates/haproxy.cfg.j2
Labels: improvement

#387 [MANOPD-86019] Move timeout_download to globals: in defaults.yaml
  kubemarine/procedures/check_iaas.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/cluster.json
  kubemarine/resources/schemas/definitions/globals.json
  kubemarine/thirdparties.py
Labels: improvement

#392 Update IN - add RHEL 8.6, 8.7 to supported OS list
  documentation/Installation.md
Labels: documentation

#391 [MANOPD-86195] K8s 1.26.3 support
  documentation/Installation.md
  kubemarine/resources/configurations/globals.yaml
Labels: improvement

#385 [MANOPD-85384]Doc update
  documentation/Maintenance.md
Labels: documentation

#381 MANOPD-84415 MANOPD-86236 Plugin manifests enrichment by python
  kubemarine.spec
  kubemarine/core/defaults.py
  kubemarine/core/utils.py
  kubemarine/patches/__init__.py
  kubemarine/patches/p1_reinstall_calico.py
  kubemarine/plugins/builtin.py
  kubemarine/plugins/calico.py
  kubemarine/plugins/kubernetes_dashboard.py
  kubemarine/plugins/local_path_provisioner.py
  kubemarine/plugins/manifest.py
  kubemarine/plugins/nginx_ingress.py
  kubemarine/plugins/yaml/calico-v3.22.2.yaml.original
  kubemarine/plugins/yaml/calico-v3.24.2.yaml.original
  kubemarine/plugins/yaml/dashboard-v2.5.1-original.yaml
  kubemarine/plugins/yaml/dashboard-v2.7.0-original.yaml
  kubemarine/plugins/yaml/local-path-provisioner-v0.0.22-original.yaml
  kubemarine/plugins/yaml/local-path-provisioner-v0.0.23-original.yaml
  kubemarine/plugins/yaml/nginx-ingress-controller-v1.2.0-original.yaml
  kubemarine/plugins/yaml/nginx-ingress-controller-v1.4.0-original.yaml
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/definitions/plugins/local-path-provisioner.json
  test/unit/plugins/__init__.py
  test/unit/plugins/test_calico.py
  test/unit/plugins/test_dashboard.py
  test/unit/plugins/test_inventory.py
  test/unit/plugins/test_local_path_provisioner.py
  test/unit/plugins/test_nginx_ingress.py
Labels: bug, improvement

#394 Added missing security headers
  kubemarine/resources/configurations/defaults.yaml
Labels: improvement

#395 [MANOPD-85659 ]Update Containerd version for all supported Kubernetes
  kubemarine/resources/configurations/globals.yaml
Labels: improvement

#388 [PDSDNREQ-7105]Add settings for Calico to enable Prometheus metrics
  documentation/Installation.md
  kubemarine/plugins/calico.py
  kubemarine/templates/plugins/calico-kube-controllers-metrics.yaml
  kubemarine/templates/plugins/calico-metrics.yaml
Labels: improvement

#398 [PSUPCLPL-12043] Doc Update - Installation guide: change RHEL prereqs
  documentation/Installation.md
Labels: documentation

#400 [PSUPCLPL-12085] Added missing security headers
  kubemarine/resources/configurations/defaults.yaml
Labels: improvement

#393 MANOPD-86292 Remove flannel and haproxy-ingress-controller plugins
  documentation/Installation.md
  examples/cluster.yaml/full-cluster.yaml
  kubemarine.spec
  kubemarine/admission.py
  kubemarine/core/defaults.py
  kubemarine/plugins/calico.py
  kubemarine/plugins/haproxy_ingress.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/definitions/plugins.json
  kubemarine/resources/schemas/definitions/plugins/flannel.json
  kubemarine/resources/schemas/definitions/plugins/haproxy-ingress-controller.json
  kubemarine/templates/plugins/flannel.yaml.j2
  kubemarine/templates/plugins/haproxy-ingress-controller.yaml.j2
Labels: improvement

#402 [MANOPD-86838] Resolve conflict of archive names in add_node and restore procedures
  kubemarine/core/utils.py
Labels: bug
