Repository Netcracker/KubeMarine, pull requests merged in 2023-12, with the labels that each got.

#562 [CPDEV-95434] - fix cleanup command
  kubemarine/procedures/upgrade.py
Labels: bug

#560 [CPDEV-95324] Update 3rd-parties
  .github/workflows/ci.yaml
  Dockerfile
  documentation/Installation.md
  kubemarine.spec
  kubemarine/core/defaults.py
  kubemarine/core/executor.py
  kubemarine/core/utils.py
  kubemarine/cri/__init__.py
  kubemarine/cri/containerd.py
  kubemarine/patches/__init__.py
  kubemarine/patches/p1_pin_kubernetes_version.py
  kubemarine/patches/software_upgrade.yaml
  kubemarine/plugins/__init__.py
  kubemarine/plugins/calico.py
  kubemarine/plugins/local_path_provisioner.py
  kubemarine/plugins/nginx_ingress.py
  kubemarine/plugins/yaml/calico-apiserver-v3.26.4-original.yaml
  kubemarine/plugins/yaml/calico-v3.26.4-original.yaml
  kubemarine/plugins/yaml/local-path-provisioner-v0.0.25-original.yaml
  kubemarine/plugins/yaml/nginx-ingress-controller-v1.8.4-original.yaml
  kubemarine/plugins/yaml/nginx-ingress-controller-v1.9.4-original.yaml
  kubemarine/resources/configurations/compatibility/internal/kubernetes_images.yaml
  kubemarine/resources/configurations/compatibility/internal/packages.yaml
  kubemarine/resources/configurations/compatibility/internal/plugins.yaml
  kubemarine/resources/configurations/compatibility/internal/thirdparties.yaml
  kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/definitions/services/kubeadm.json
  pyproject.toml
  scripts/ci/build_binary.py
  scripts/ci/custom-hooks/hook-cryptography.py
  scripts/ci/install_package.py
  test/unit/plugins/test_calico.py
  test/unit/plugins/test_nginx_ingress.py
  test/unit/test_audit.py
  test/unit/test_coredns.py
  test/unit/test_kubernetes.py
Labels: feature

#564 [CPREQ-8282]-Certify_Kubemarine_for_RHEL_8.9
  documentation/Installation.md
  kubemarine/resources/configurations/globals.yaml
Labels: feature

#567 Add note about docker shim removal
  kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml
Labels: documentation

#565 [CPDEV-95468] Calico non-overlay
  documentation/Installation.md
  kubemarine/resources/schemas/definitions/plugins/calico.json
Labels: bug

#570 [PSUPCLPL-13377] Instructions for cryptographic cipher suites
  documentation/internal/Hardening.md
Labels: documentation

#572 [CPDEV-82348] Manage primitive values represented as strings
  kubemarine/core/defaults.py
  kubemarine/core/utils.py
  kubemarine/cri/containerd.py
  kubemarine/modprobe.py
  kubemarine/plugins/calico.py
  kubemarine/resources/schemas/definitions/services/sysctl.json
  kubemarine/sysctl.py
  kubemarine/system.py
  test/unit/test_defaults.py
Labels: improvement

#569 [CPDEV-95723] Support release candidate version
  kubemarine/admission.py
  kubemarine/core/defaults.py
  kubemarine/core/utils.py
  kubemarine/jinja.py
  kubemarine/kubernetes/__init__.py
  kubemarine/kubernetes_accounts.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/upgrade.py
  kubemarine/resources/configurations/defaults.yaml
  scripts/thirdparties/src/compatibility.py
  test/unit/test_upgrade.py
Labels: improvement

#571 [CPDEV-95920] Support KubeProxyConfiguration as services.kubeadm_kube-proxy section
  documentation/Installation.md
  kubemarine/kubernetes/__init__.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/definitions/services.json
  kubemarine/resources/schemas/definitions/services/kubeadm_kube-proxy.json
Labels: feature

#579 [PSUPCLPL-14291] - add new TG section for kubemarine docker run issue
  documentation/Troubleshooting.md
Labels: documentation

#566 Update Maintenance.md
  documentation/Maintenance.md
Labels: documentation

#582 [CPDEV-96588] - apply kubeadm-config during upgrade
  kubemarine/procedures/upgrade.py
Labels: bug
