Repository Netcracker/KubeMarine, pull requests merged in 2023-05, with the labels that each got.

#421 [MANOPD-87506] Wrong format for ipv6 address and port in kubeconfig
  kubemarine/kubernetes/__init__.py
Labels: bug

#429 Default admission test & doc
  documentation/Installation.md
  test/unit/test_admission.py
  test/unit/test_upgrade.py
Labels: improvement

#432 [MANOPD-1] Update Installation.md about minimal prerequisites for Deployment Node
  documentation/Installation.md
Labels: documentation

#426 MANOPD-87827 Ensure thirdparties management approach
  kubemarine/__main__.py
  kubemarine/core/cluster.py
  kubemarine/core/defaults.py
  kubemarine/core/errors.py
  kubemarine/core/flow.py
  kubemarine/core/resources.py
  kubemarine/core/static.py
  kubemarine/core/utils.py
  kubemarine/k8s_certs.py
  kubemarine/kubernetes/__init__.py
  kubemarine/procedures/add_node.py
  kubemarine/procedures/backup.py
  kubemarine/procedures/cert_renew.py
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/do.py
  kubemarine/procedures/install.py
  kubemarine/procedures/manage_psp.py
  kubemarine/procedures/manage_pss.py
  kubemarine/procedures/migrate_cri.py
  kubemarine/procedures/migrate_kubemarine.py
  kubemarine/procedures/reboot.py
  kubemarine/procedures/remove_node.py
  kubemarine/procedures/restore.py
  kubemarine/procedures/upgrade.py
  kubemarine/resources/configurations/compatibility/internal/packages.yaml
  kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml
  scripts/thirdparties/src/compatibility.py
  scripts/thirdparties/src/software/kubernetes_images.py
  scripts/thirdparties/src/software/plugins.py
  scripts/thirdparties/src/software/thirdparties.py
  scripts/thirdparties/src/tracker.py
  test/unit/core/test_flow.py
  test/unit/core/test_run_actions.py
  test/unit/test_upgrade.py
  test/unit/tools/thirdparties/stub.py
  test/unit/tools/thirdparties/test_sync.py
  test/unit/utils.py
Labels: improvement

#440 Fix binary build for macos arm64
  pyproject.toml
Labels: bug

#356 [MANOPD-82728]Complex namespaces in 'migrate_pss' procedure
  documentation/Maintenance.md
  kubemarine/admission.py
Labels: bug, question

#438 [MANOPD-87835] Rocky Linux 8.6, 8.7 support
  documentation/Installation.md
  kubemarine/resources/configurations/globals.yaml
  kubemarine/system.py
Labels: improvement, feature

#424 [MANOPD-84744] fix remove_node.py in case of custom etc_hosts value
  documentation/Installation.md
  kubemarine/core/defaults.py
  kubemarine/coredns.py
  kubemarine/procedures/install.py
  kubemarine/procedures/remove_node.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/definitions/services.json
  kubemarine/resources/schemas/definitions/services/coredns.json
  kubemarine/system.py
  test/unit/test_coredns.py
Labels: bug, improvement

#428 Documentation Review
  documentation/Installation.md
  documentation/Troubleshooting.md
  kubemarine/resources/schemas/definitions/plugins/installation/helm.json
Labels: documentation

#441 Update default version in Installation.md
  documentation/Installation.md
Labels: documentation

#434 [MANOPD-87147] Improving colors
  documentation/Logging.md
  kubemarine/core/log.py
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/check_paas.py
  kubemarine/resources/configurations/globals.yaml
  kubemarine/testsuite.py
Labels: improvement

#449 W/A Python issue 12782 in unit tests.
  test/unit/test_migrate_kubemarine.py
  test/unit/test_upgrade.py
Labels: bug

#447 [MANOPD-81667] fix make_finalized_inventory
  kubemarine/admission.py
  kubemarine/core/cluster.py
Labels: bug

#452 [MANOPD-88703] Added RHEL 8.8 support
  kubemarine/resources/configurations/globals.yaml
Labels: feature

#451 [MANOPD-88830] Adding new requirements before installing a cluster on RHEL 8-based nodes
  documentation/Installation.md
Labels: documentation

#446 [MANOPD-88530] Update task "services.system.modprobe.rules" for different os in Check_PaaS
  kubemarine/procedures/check_paas.py
Labels: improvement
