Repository Netcracker/KubeMarine, pull requests merged in 2023-04, with the labels that each got.

#382 PSUPCLPL-11975 - Fix for issue #365
  documentation/Installation.md
  kubemarine/procedures/check_paas.py
  kubemarine/thirdparties.py
Labels: bug

#399 MANOPD-86805 Radon cyclomatic complexity check
  .github/workflows/tests.yaml
Labels: improvement

#390 [MANOPD-1] Update Installation.md about new versions Kubernetes
  documentation/Installation.md
Labels: documentation

#396 [MANOPD-85860] Add Missing TCP Ports in check_iaas procedure
  documentation/Installation.md
  kubemarine/procedures/check_iaas.py
Labels: bug

#410 [PSUPCLPL-12171] Make expect timeouts customized
  documentation/Installation.md
  kubemarine/kubernetes/__init__.py
  kubemarine/plugins/__init__.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/configurations/globals.yaml
  kubemarine/resources/schemas/definitions/globals.json
Labels: improvement

#406 MANOPD-86915 Missed /root/.kube/config in backup & restore
  kubemarine/procedures/backup.py
Labels: bug

#405 [MANOPD-86862] - add TG for vrrp in calico
  documentation/Troubleshooting.md
Labels: documentation

#408 Add issue to Troubleshooting.md
  documentation/Troubleshooting.md
Labels: documentation

#413 Doc update: add new parameters in globals section of IN
  documentation/Installation.md
Labels: documentation

#415 [MANOPD-87367] Check_iaas procedure doesn't check tcp ports 9091, 9094 and 10254
  kubemarine/procedures/check_iaas.py
Labels: improvement

#417 [MANOPD-87294] - fix version check
  kubemarine/procedures/check_paas.py
Labels: bug

#416 [MANOPD-87304] Ci multiple kuber versions
  .github/workflows/test_install.yaml
  ci/default_cluster.yaml
  ci/default_config.yaml
  ci/extended_cluster.yaml
  kubemarine/admission.py
  kubemarine/core/defaults.py
  kubemarine/kubernetes/__init__.py
  kubemarine/resources/configurations/defaults.yaml
Labels: improvement

#412 [MANOPD-87043] There is no information about ports 9091 and 9094 in the installation guide in the open TCP ports section
  documentation/Installation.md
Labels: documentation

#403 [MANOPD-86649] Installation on IPv6 env fails
  documentation/Installation.md
  examples/cluster.yaml/full-cluster.yaml
  kubemarine/core/defaults.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/definitions/services/modprobe.json
  kubemarine/system.py
Labels: bug, documentation, improvement

#397 [MANOPD-1] Update default version kubernetes
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/definitions/services/kubeadm.json
Labels: improvement, question, feature
