Repository Netcracker/KubeMarine, pull requests merged in 2023-02, with the labels that each got.

#354 [MANOPD-84427] : No busybox version 1.31.2
  kubemarine/resources/configurations/globals.yaml
  kubemarine/resources/schemas/definitions/plugins/local-path-provisioner.json
Labels: bug, dependencies

#348 MANOPD-84124 Fix unnecessary reboot when nothing to remove / upgrade
  kubemarine/apt.py
  kubemarine/packages.py
  kubemarine/procedures/install.py
  kubemarine/yum.py
Labels: improvement

#345 Kubemarine: procedure for removing default taint on nodes having the roles of master and worker
  documentation/Installation.md
  documentation/Maintenance.md
  kubemarine/kubernetes/__init__.py
  kubemarine/procedures/upgrade.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/definitions/services/kubeadm.json
  test/unit/test_thirdparties.py
Labels: improvement

#351 Implemenent patch to change template to config plugin procedure type
  kubemarine/patches/__init__.py
  kubemarine/patches/p2_do_render_config.py
Labels: bug, improvement

#357 Documentation Review and Update
  documentation/Installation.md
Labels: documentation

#355 Fix ci dump location
  .github/workflows/test_install.yaml
Labels: improvement

#347 [MANOPD-84029] Status of resources
  kubemarine/plugins/__init__.py
  kubemarine/resources/configurations/globals.yaml
Labels: bug

#352 [MANOPD-83794] node-specific settings for control-plane via patches
  documentation/Installation.md
  kubemarine.spec
  kubemarine/kubernetes/__init__.py
  kubemarine/procedures/install.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/definitions/services.json
  kubemarine/resources/schemas/definitions/services/kubeadm_patches.json
  kubemarine/templates/patches/control-plane-pod.json.j2
  kubemarine/templates/patches/kubelet.yaml.j2
Labels: improvement

#346 MANOPD-84031 Input files encoding rework and non-ASCII upload
  documentation/Installation.md
  kubemarine/admission.py
  kubemarine/apt.py
  kubemarine/core/cluster.py
  kubemarine/core/defaults.py
  kubemarine/core/flow.py
  kubemarine/core/group.py
  kubemarine/core/resources.py
  kubemarine/core/schema.py
  kubemarine/core/static.py
  kubemarine/core/utils.py
  kubemarine/demo.py
  kubemarine/haproxy.py
  kubemarine/keepalived.py
  kubemarine/kubernetes/__init__.py
  kubemarine/kubernetes_accounts.py
  kubemarine/plugins/__init__.py
  kubemarine/plugins/calico.py
  kubemarine/plugins/nginx_ingress.py
  kubemarine/plugins/yaml/calico-v3.24.2.yaml.original
  kubemarine/procedures/backup.py
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/restore.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/definitions/services/packages.json
  kubemarine/resources/schemas/definitions/services/thirdparties.json
  kubemarine/system.py
  kubemarine/testsuite.py
  kubemarine/thirdparties.py
  kubemarine/yum.py
  test/unit/core/test_schema.py
  test/unit/test_demo.py
Labels: bug, documentation

#353 How to use JSON schemas in IDEs
  documentation/Installation.md
  documentation/Maintenance.md
Labels: documentation

#358 MANOPD-83709 KubeMarine as python package on pypi.org
  .dockerignore
  .github/workflows/build.yaml
  .github/workflows/patch.yaml
  .github/workflows/pypi.yaml
  .github/workflows/release.yaml
  .github/workflows/test_install.yaml
  .github/workflows/tests.yaml
  Dockerfile
  MANIFEST.in
  README.md
  bin/kubemarine
  bin/kubemarine.cmd
  build.sh
  documentation/Installation.md
  kubemarine.spec
  pyproject.toml
  requirements.txt
  requirements_nt.txt
  setup.cfg
  setup.py
  test/unit/core/test_schema.py
  test/unit/plugins/test_template.py
Labels: documentation, feature

#361 Add RHEL8.7 support
  kubemarine/resources/configurations/globals.yaml
Labels: improvement

#364 Fix patch autodeletion workflow
  .github/workflows/release.yaml
Labels: bug
