Repository Netcracker/KubeMarine, pull requests merged in 2023-10, with the labels that each got.

#510 [CPDEV-92546] Install the Calico API server to enable management of Calico API "projectcalico.org/v3"
  ci/default_cluster.yaml
  ci/extended_cluster.yaml
  documentation/Installation.md
  documentation/Kubecheck.md
  documentation/Maintenance.md
  documentation/internal/Patches.md
  examples/cluster.yaml/full-cluster.yaml
  kubemarine/admission.py
  kubemarine/core/utils.py
  kubemarine/core/yaml_merger.py
  kubemarine/kubernetes/__init__.py
  kubemarine/kubernetes/object.py
  kubemarine/kubernetes/secrets.py
  kubemarine/patches/__init__.py
  kubemarine/patches/p2_reconfigure_audit_policy.py
  kubemarine/plugins/__init__.py
  kubemarine/plugins/builtin.py
  kubemarine/plugins/calico.py
  kubemarine/plugins/kubernetes_dashboard.py
  kubemarine/plugins/local_path_provisioner.py
  kubemarine/plugins/manifest.py
  kubemarine/plugins/nginx_ingress.py
  kubemarine/plugins/yaml/calico-apiserver-v3.24.2-original.yaml
  kubemarine/plugins/yaml/calico-apiserver-v3.25.1-original.yaml
  kubemarine/plugins/yaml/calico-apiserver-v3.26.1-original.yaml
  kubemarine/procedures/cert_renew.py
  kubemarine/procedures/check_paas.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/configurations/globals.yaml
  kubemarine/resources/schemas/cert_renew.json
  kubemarine/resources/schemas/definitions/plugins/calico.json
  kubemarine/resources/schemas/definitions/plugins/nginx-ingress-controller.json
  scripts/thirdparties/src/software/plugins.py
  test/unit/plugins/__init__.py
  test/unit/plugins/test_calico.py
  test/unit/plugins/test_dashboard.py
  test/unit/plugins/test_inventory.py
  test/unit/plugins/test_local_path_provisioner.py
  test/unit/plugins/test_nginx_ingress.py
  test/unit/tools/thirdparties/stub.py
  test/unit/tools/thirdparties/test_sync.py
Labels: documentation, feature

#515 CPDEV-93439 Cannot enable PSS without calico-apiserver
  kubemarine/admission.py
  kubemarine/plugins/builtin.py
  kubemarine/plugins/calico.py
  kubemarine/plugins/kubernetes_dashboard.py
  kubemarine/plugins/local_path_provisioner.py
  kubemarine/plugins/manifest.py
  kubemarine/plugins/nginx_ingress.py
Labels: bug

#522 [CPDEV-91476] Insert license only to protected branches
  .github/workflows/tests.yaml
Labels: improvement

#516 [CPDEV-93148] [CPDEV-93149] Clarify kubernetes audit rules
  documentation/Installation.md
  kubemarine/core/resources.py
  kubemarine/demo.py
  kubemarine/patches/__init__.py
  kubemarine/patches/p1_enable_calico_audit.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/definitions/services/audit.json
Labels: documentation, improvement

#517 [CPDEV-93591] Expose Calico Typha metrics
  documentation/Installation.md
  documentation/Maintenance.md
  kubemarine/patches/__init__.py
  kubemarine/patches/p2_calico_typha_metrics.py
  kubemarine/plugins/builtin.py
  kubemarine/plugins/calico.py
  kubemarine/plugins/manifest.py
  kubemarine/procedures/check_iaas.py
  kubemarine/resources/schemas/definitions/plugins/calico.json
  kubemarine/templates/plugins/calico-typha-metrics.yaml
  test/unit/plugins/test_builtin.py
  test/unit/plugins/test_calico.py
Labels: documentation, improvement

#520 [CPDEV-93723] Restore from backup holding another Kubernetes version
  kubemarine/core/defaults.py
  kubemarine/core/flow.py
  kubemarine/core/utils.py
  kubemarine/kubernetes/__init__.py
  kubemarine/procedures/backup.py
  kubemarine/procedures/restore.py
  test/unit/core/test_schema.py
  test/unit/test_restore.py
Labels: bug

#525 [CPDEV-93091] Add dashboard ingress check to check_paas dashboard test
  .github/workflows/integration_tests.yaml
  kubemarine/procedures/check_paas.py
Labels: improvement

#518 [PSUPCLPL-7074]Update TG: Add Etcdserver Timeout Issue
  documentation/Troubleshooting.md
Labels: documentation

#523 [CPDEV-93827] - add new containerd format support
  documentation/Installation.md
  kubemarine/core/defaults.py
  kubemarine/core/utils.py
  kubemarine/cri/containerd.py
  kubemarine/patches/__init__.py
  kubemarine/patches/p3_reconfigure_registries.py
  kubemarine/procedures/backup.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/restore.py
  kubemarine/resources/schemas/definitions/services/cri.json
  pyproject.toml
  test/unit/core/test_registry.py
  test/unit/test_cri_enrichment.py
Labels: feature

#521 [CPREQ-7712] Kubemarine version should start with 'v'
  .github/workflows/patch.yaml
  kubemarine/version
  pyproject.toml
Labels: improvement

#526 [CPDEV-93994] Minor fixes and tests refactoring
  documentation/Kubecheck.md
  documentation/Maintenance.md
  kubemarine/__main__.py
  kubemarine/core/resources.py
  kubemarine/core/schema.py
  kubemarine/demo.py
  kubemarine/procedures/__init__.py
  kubemarine/procedures/add_node.py
  kubemarine/procedures/backup.py
  kubemarine/procedures/cert_renew.py
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/install.py
  kubemarine/procedures/manage_psp.py
  kubemarine/procedures/manage_pss.py
  kubemarine/procedures/migrate_cri.py
  kubemarine/procedures/migrate_kubemarine.py
  kubemarine/procedures/reboot.py
  kubemarine/procedures/remove_node.py
  kubemarine/procedures/restore.py
  kubemarine/procedures/upgrade.py
  test/unit/core/test_cluster.py
  test/unit/core/test_env.py
  test/unit/core/test_flow.py
  test/unit/core/test_schema.py
  test/unit/plugins/test_nginx_ingress.py
  test/unit/test_add_node.py
  test/unit/test_backup.py
  test/unit/test_check_paas.py
  test/unit/test_inventory.py
  test/unit/test_k8s_cert.py
  test/unit/test_manage_psp.py
  test/unit/test_manage_pss.py
  test/unit/test_migrate_cri.py
  test/unit/test_migrate_kubemarine.py
  test/unit/test_packages.py
  test/unit/test_restore.py
  test/unit/test_upgrade.py
Labels: improvement

#527 [CPDEV-94061] Restore resolv.conf before restoring of thirdparties
  documentation/Maintenance.md
  kubemarine/core/defaults.py
  kubemarine/core/utils.py
  kubemarine/procedures/restore.py
  kubemarine/thirdparties.py
  test/unit/test_restore.py
Labels: bug
