Repository Netcracker/KubeMarine, pull requests merged in 2023-01, with the labels that each got.

#326 [PSUPCLPL-11428] Update defaults.yaml and global.yaml - parametrize local-path-provisioner and busybox image version
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/configurations/globals.yaml
Labels: bug

#321 [PSUPCLPL-11380] Doc update: how to change cluster CIDR guide
  documentation/Maintenance.md
Labels: documentation

#325 [PSUPCLPL-11380] Update TG - add Random 504 Error on Ingresses chapter
  documentation/Troubleshooting.md
Labels: documentation

#329 Make paramiko common for Linux and Windows deployers
  requirements.txt
  requirements_nt.txt
Labels: bug

#330 [MANOPD-81954] Data encryption
  documentation/Maintenance.md
Labels: documentation

#331 Test ci install
  .github/workflows/test_install.yaml
  ci/default_config.yaml
  ci/extended_config.yaml
  kubemarine/procedures/check_iaas.py
  kubemarine/system.py
Labels: improvement

#332 Cumulative points fixes
  kubemarine/core/flow.py
  kubemarine/procedures/install.py
  kubemarine/procedures/reboot.py
  kubemarine/procedures/restore.py
  kubemarine/system.py
  test/unit/core/test_flow.py
  test/unit/test_demo.py
Labels: bug, improvement

#333 MANOPD-82393 Final summary report
  kubemarine.spec
  kubemarine/core/cluster.py
  kubemarine/core/flow.py
  kubemarine/core/resources.py
  kubemarine/core/utils.py
  kubemarine/kubernetes/__init__.py
  kubemarine/kubernetes_accounts.py
  kubemarine/plugins/kubernetes_dashboard.py
  kubemarine/procedures/add_node.py
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/do.py
  kubemarine/procedures/install.py
  kubemarine/procedures/remove_node.py
  kubemarine/procedures/upgrade.py
  kubemarine/resources/configurations/defaults.yaml
  test/unit/core/test_run_actions.py
  test/unit/test_kubernetes.py
Labels: feature

#336 Remove dead validation
  kubemarine/admission.py
  kubemarine/apparmor.py
  kubemarine/core/cluster.py
  kubemarine/core/defaults.py
  kubemarine/core/errors.py
  kubemarine/cri/__init__.py
  kubemarine/k8s_certs.py
  kubemarine/keepalived.py
  kubemarine/kubernetes/__init__.py
  kubemarine/kubernetes_accounts.py
  kubemarine/packages.py
  kubemarine/plugins/__init__.py
  kubemarine/plugins/nginx_ingress.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/install.py
  kubemarine/procedures/migrate_cri.py
  kubemarine/procedures/upgrade.py
  kubemarine/selinux.py
  kubemarine/system.py
  kubemarine/thirdparties.py
  test/unit/k8s_cert_test.py
  test/unit/plugins/test_inventory.py
  test/unit/plugins/test_nginx_ingress.py
  test/unit/plugins/test_template.py
  test/unit/test_admission.py
  test/unit/test_check_paas.py
  test/unit/test_inventory.py
  test/unit/test_manage_psp.py
  test/unit/test_manage_pss.py
  test/unit/test_migrate_cri.py
  test/unit/test_packages.py
  test/unit/test_thirdparties.py
  test/unit/test_upgrade.py
Labels: improvement

#334 [MANOPD-82072] k8s nodes are "not ready" periodically
  documentation/Troubleshooting.md
Labels: documentation

#338 MANOPD-83734 Actualize and ensure mandatory thirdparty packages
  ci/default_config.yaml
  ci/extended_config.yaml
  documentation/Installation.md
  documentation/Kubecheck.md
  documentation/Maintenance.md
  kubemarine/apt.py
  kubemarine/audit.py
  kubemarine/core/cluster.py
  kubemarine/core/defaults.py
  kubemarine/core/executor.py
  kubemarine/core/group.py
  kubemarine/packages.py
  kubemarine/patches/__init__.py
  kubemarine/patches/p1_mandatory_packages_off.py
  kubemarine/plugins/__init__.py
  kubemarine/procedures/add_node.py
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/do.py
  kubemarine/procedures/install.py
  kubemarine/procedures/upgrade.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/configurations/globals.yaml
  kubemarine/resources/schemas/definitions/services/packages.json
  kubemarine/resources/schemas/definitions/services/packages/associations.json
  kubemarine/resources/schemas/migrate_cri.json
  kubemarine/resources/schemas/upgrade.json
  kubemarine/system.py
  kubemarine/thirdparties.py
  kubemarine/yum.py
  test/unit/core/test_executor.py
  test/unit/test_audit.py
  test/unit/test_haproxy.py
  test/unit/test_install.py
  test/unit/test_keepalived.py
  test/unit/test_packages.py
Labels: bug, documentation, feature

#337 [PSUPCLPL-11612] fix calico_yaml path in case of non-default dump_location
  kubemarine/plugins/__init__.py
  kubemarine/plugins/calico.py
  kubemarine/plugins/yaml/calico-v3.24.1.yaml.original
  kubemarine/plugins/yaml/calico-v3.24.2.yaml.original
  kubemarine/resources/configurations/defaults.yaml
Labels: bug

#335 Update Maintenance.md
  documentation/Maintenance.md
Labels: documentation

#340 [MANOPD-82072]IaaS_Check: Check kernel version on nodes
  documentation/Kubecheck.md
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/check_paas.py
  kubemarine/resources/configurations/globals.yaml
Labels: improvement

#341 MANOPD-82393 Summary fixes and improvements
  .gitignore
  kubemarine/core/flow.py
  kubemarine/core/summary.py
  kubemarine/core/utils.py
  kubemarine/kubernetes/__init__.py
  kubemarine/kubernetes_accounts.py
  kubemarine/plugins/__init__.py
  kubemarine/plugins/kubernetes_dashboard.py
  kubemarine/procedures/install.py
  kubemarine/procedures/remove_node.py
  test/unit/core/test_flow.py
  test/unit/test_kubernetes.py
Labels: bug, improvement
