Repository Netcracker/KubeMarine, pull requests merged in 2023-11, with the labels that each got.

#529 Kubelet server certificate improvement
  documentation/Maintenance.md
  documentation/Troubleshooting.md
  kubemarine/k8s_certs.py
Labels: documentation, improvement

#532 [CPDEV-84690] Improvement and fixes in Keepalived installation and removing balancers
  documentation/Maintenance.md
  kubemarine/controlplane.py
  kubemarine/core/cluster.py
  kubemarine/core/defaults.py
  kubemarine/core/resources.py
  kubemarine/core/utils.py
  kubemarine/haproxy.py
  kubemarine/keepalived.py
  kubemarine/kubernetes/__init__.py
  kubemarine/patches/__init__.py
  kubemarine/patches/p0_bind_vrrp_ips_interfaces.py
  kubemarine/procedures/add_node.py
  kubemarine/procedures/install.py
  kubemarine/procedures/remove_node.py
  kubemarine/resources/schemas/add_node.json
  kubemarine/system.py
  test/unit/core/test_flow.py
  test/unit/test_coredns.py
  test/unit/test_defaults.py
  test/unit/test_inventory.py
  test/unit/test_keepalived.py
  test/unit/test_remove_node.py
  test/unit/test_thirdparties.py
Labels: bug, documentation

#539 [CPREQ-6280] added upgrade recommendation notes
  documentation/Maintenance.md
Labels: documentation

#537 [CPDEV-94459] Backup custom apt repositories
  documentation/Maintenance.md
  kubemarine/procedures/backup.py
Labels: bug

#542 k8s v1.28.3 support
  kubemarine/resources/configurations/compatibility/internal/kubernetes_images.yaml
  kubemarine/resources/configurations/compatibility/internal/packages.yaml
  kubemarine/resources/configurations/compatibility/internal/plugins.yaml
  kubemarine/resources/configurations/compatibility/internal/thirdparties.yaml
  kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml
Labels: improvement

#473 [CPDEV-94365] Add support for RHEL9 family, SELinux
  documentation/Installation.md
  kubemarine/admission.py
  kubemarine/core/cluster.py
  kubemarine/core/group.py
  kubemarine/keepalived.py
  kubemarine/packages.py
  kubemarine/patches/software_upgrade.yaml
  kubemarine/procedures/backup.py
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/migrate_kubemarine.py
  kubemarine/resources/configurations/compatibility/internal/packages.yaml
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/configurations/globals.yaml
  kubemarine/resources/etalons/patches/software_upgrade.yaml
  kubemarine/resources/schemas/definitions/services/modprobe.json
  kubemarine/resources/schemas/definitions/services/packages/associations.json
  kubemarine/selinux.py
  kubemarine/system.py
  scripts/thirdparties/src/software/packages.py
  test/unit/test_migrate_kubemarine.py
  test/unit/test_upgrade.py
Labels: improvement, external

#535 [CPDEV-94449] Add RockyLinux 8.8 support
  documentation/Installation.md
  kubemarine/resources/configurations/globals.yaml
Labels: improvement

#533 [CPDEV-94200] Support new containerd registries endpoint format in migrate_cri
  documentation/Maintenance.md
  kubemarine/core/defaults.py
  kubemarine/core/errors.py
  kubemarine/core/utils.py
  kubemarine/cri/containerd.py
  kubemarine/packages.py
  kubemarine/procedures/migrate_cri.py
  kubemarine/resources/schemas/migrate_cri.json
  kubemarine/thirdparties.py
  test/unit/test_migrate_cri.py
Labels: documentation, feature

#540 [CPDEV-94486] Add sysctl and audit rules validation
  documentation/Kubecheck.md
  kubemarine/audit.py
  kubemarine/demo.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/install.py
  kubemarine/sysctl.py
  kubemarine/system.py
  test/unit/test_audit.py
Labels: improvement

#548 Increase mypy dependency
  kubemarine/admission.py
  kubemarine/core/connections.py
  kubemarine/core/executor.py
  kubemarine/core/log.py
  kubemarine/core/utils.py
  kubemarine/core/yaml_merger.py
  kubemarine/demo.py
  kubemarine/procedures/check_paas.py
  kubemarine/resources/scripts/check_url_availability.py
  pyproject.toml
Labels: bug

#545 [CPDEV-94593] Upgrade to v1.28.3 issue
  documentation/Troubleshooting.md
Labels: documentation

#536 [CPDEV-94448] Improve check_paas checks and logging
  documentation/Kubecheck.md
  kubemarine/core/utils.py
  kubemarine/kubernetes/__init__.py
  kubemarine/plugins/builtin.py
  kubemarine/plugins/calico.py
  kubemarine/procedures/check_paas.py
  kubemarine/resources/schemas/definitions/services/kubeadm.json
  scripts/thirdparties/src/software/plugins.py
  test/unit/plugins/__init__.py
Labels: improvement

#546 [CPDEV-50513] Add nf_conntrack_max and NetworkManager config recommended for calico
  documentation/Installation.md
  kubemarine/patches/__init__.py
  kubemarine/patches/p1_set_sysctl_variables.py
  kubemarine/resources/configurations/defaults.yaml
Labels: documentation, improvement

#541 [CPREQ-7974] Kubernetes hardening
  documentation/Maintenance.md
  documentation/Troubleshooting.md
  documentation/internal/Hardening.md
Labels: documentation, feature

#552 [CPDEV-95071] Add nf_conntrack to the list of modprobe's modules
  kubemarine/patches/p1_set_sysctl_variables.py
  kubemarine/resources/configurations/defaults.yaml
Labels: bug

#554 [CPDEV-95240] Reconfigure modprobe if configuration is outdated
  kubemarine/modprobe.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/install.py
  kubemarine/system.py
Labels: bug

#556 Return patches from v0.24.0
  kubemarine/patches/__init__.py
  kubemarine/patches/p0_bind_vrrp_ips_interfaces.py
  kubemarine/patches/p1_set_sysctl_variables.py
Labels: bug

#551 [CPDEV-94547] Rework network connectivity check and implement VRRP IP check
  documentation/Installation.md
  documentation/Kubecheck.md
  kubemarine/core/cluster.py
  kubemarine/core/executor.py
  kubemarine/core/group.py
  kubemarine/procedures/check_iaas.py
  kubemarine/resources/scripts/simple_port_client.py
  kubemarine/resources/scripts/simple_port_listener.py
  kubemarine/resources/scripts/simple_tcp_listener.py
  test/unit/core/test_executor.py
Labels: documentation, feature

#553 [CPDEV-93171] - do not export kubernetes resources by default
  documentation/Maintenance.md
  kubemarine/procedures/backup.py
  kubemarine/resources/schemas/backup.json
  test/unit/test_backup.py
Labels: bug, improvement

#557 [CPDEV-93171] - clean kubernetes tmp dir before upgrade
  documentation/Maintenance.md
  kubemarine/procedures/upgrade.py
  test/unit/test_upgrade.py
Labels: bug
