Repository Netcracker/KubeMarine, pull requests merged in 2024-06, with the labels that each got.

#668 [PSUPCLPL-15568] Certificate specification
  documentation/Installation.md
Labels: documentation

#669 [CPDEV-102476] Implement patch that reconfigures Kubernetes audit
  kubemarine/patches/__init__.py
  kubemarine/patches/p3_reconfigure_audit.py
Labels: bug

#675 [CPDEV-102250] Remove Cloud Provider Plugin support
  documentation/Installation.md
  kubemarine/kubernetes/components.py
Labels: documentation

#672 [CPDEV-103323] No initial timeout for etcd check
  kubemarine/etcd.py
  kubemarine/procedures/check_paas.py
  kubemarine/resources/configurations/globals.yaml
Labels: improvement

#671 [CPDEV-103189] Different improvements in SSH connections usage
  kubemarine/core/connections.py
  kubemarine/core/executor.py
  kubemarine/core/group.py
  kubemarine/core/utils.py
  kubemarine/demo.py
  kubemarine/kubernetes/secrets.py
  kubemarine/plugins/__init__.py
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/restore.py
  kubemarine/resources/configurations/globals.yaml
  kubemarine/thirdparties.py
Labels: improvement
