Repository Netcracker/KubeMarine, pull requests merged in 2024-01, with the labels that each got.

#575 [PSUPCLPL-14309] Maintenance guide update
  README.md
  documentation/Installation.md
  documentation/Maintenance.md
Labels: documentation

#585 [CPDEV-96929] Support of granular 3rd party updates per specific Kubernetes version
  documentation/Maintenance.md
  kubemarine/kubernetes/__init__.py
  scripts/thirdparties/src/software/plugins.py
  scripts/thirdparties/src/software/thirdparties.py
  test/unit/test_upgrade.py
  test/unit/tools/thirdparties/test_sync.py
Labels: feature

#588 [CPREQ-8436] Clarify documentation Hardening.md: Disable Anonymous Authentication for kube-apiserver
  documentation/internal/Hardening.md
Labels: documentation

#589 Allow plugins without installation procedures
  kubemarine/thirdparties.py
Labels: improvement

#590 Fix scheduler's patch name
  kubemarine/kubernetes/__init__.py
Labels: bug

#591 Improvements and fixes in GitHub workflows
  .github/workflows/integration_tests.yaml
  .github/workflows/tests.yaml
  kubemarine/plugins/yaml/calico-v3.26.1-original.yaml
  kubemarine/plugins/yaml/nginx-ingress-controller-v1.8.1-original.yaml
Labels: bug
