Repository Netcracker/KubeMarine, pull requests merged in 2024-04, with the labels that each got.

#629 [CPDEV-100505] Always dump finalized inventory for all procedures except `do`
  kubemarine/core/flow.py
  kubemarine/core/resources.py
  kubemarine/demo.py
  kubemarine/procedures/do.py
  test/unit/core/test_run_actions.py
  test/unit/test_do.py
  test/unit/utils.py
Labels: bug

#631 Kubecheck doc update
  documentation/Kubecheck.md
Labels: documentation

#633 [CPDEV-98472]-Enabling_strong_crypto_support_by_default_for_kubelet
  kubemarine/patches/__init__.py
  kubemarine/patches/strong_cipher_suits_for_kubelet.py
  kubemarine/resources/configurations/defaults.yaml
Labels: improvement

#636 [CPDEV-100414] Install and check thirdparties skipping SSL verification
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/check_paas.py
  kubemarine/resources/scripts/check_url_availability.py
  kubemarine/thirdparties.py
Labels: improvement

#637 [PSUPCLPL-15188] Add a note about balancers to add_node procedure to MG
  documentation/Maintenance.md
Labels: documentation

#643 [CPREQ-9137] - RockyLinux 9.3 support for Kubemarine
  documentation/Installation.md
  kubemarine/resources/configurations/globals.yaml
Labels: improvement

#628 [CPDEV-95355] add_node and remove_node if there are notready workers
  documentation/Maintenance.md
  kubemarine/core/cluster.py
  kubemarine/coredns.py
  kubemarine/packages.py
  kubemarine/procedures/install.py
  test/unit/core/test_flow.py
Labels: improvement

#639 [CPDEV-100486] Support kernel parameters/modules per group/node
  documentation/Installation.md
  kubemarine/core/cluster.py
  kubemarine/core/defaults.py
  kubemarine/core/inventory.py
  kubemarine/core/resources.py
  kubemarine/core/schema.py
  kubemarine/core/utils.py
  kubemarine/core/yaml_merger.py
  kubemarine/jinja.py
  kubemarine/kubernetes/__init__.py
  kubemarine/kubernetes/components.py
  kubemarine/modprobe.py
  kubemarine/patches/__init__.py
  kubemarine/patches/preserve_compatibility_kernel.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/install.py
  kubemarine/procedures/upgrade.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/cluster.json
  kubemarine/resources/schemas/definitions/common/node_ref.json
  kubemarine/resources/schemas/definitions/node.json
  kubemarine/resources/schemas/definitions/node_defaults.json
  kubemarine/resources/schemas/definitions/patch.json
  kubemarine/resources/schemas/definitions/plugins/installation/ansible.json
  kubemarine/resources/schemas/definitions/plugins/installation/shell.json
  kubemarine/resources/schemas/definitions/plugins/installation/template.json
  kubemarine/resources/schemas/definitions/services/kubeadm_kubelet.json
  kubemarine/resources/schemas/definitions/services/kubeadm_patches.json
  kubemarine/resources/schemas/definitions/services/modprobe.json
  kubemarine/resources/schemas/definitions/services/sysctl.json
  kubemarine/resources/schemas/definitions/services/thirdparties.json
  kubemarine/sysctl.py
  kubemarine/system.py
  test/unit/core/test_schema.py
  test/unit/test_defaults.py
  test/unit/test_modprobe.py
  test/unit/test_sysctl.py
Labels: bug, feature
