Repository Netcracker/KubeMarine, pull requests merged in 2024-03, with the labels that each got.

#614 Avoid interactive constants (exit) from site module
  kubemarine/procedures/migrate_kubemarine.py
  kubemarine/resources/scripts/check_url_availability.py
  kubemarine/resources/scripts/simple_port_client.py
  kubemarine/resources/scripts/simple_port_listener.py
  scripts/ci/build_binary.py
Labels: bug

#613 Print supported configurations of 3rd-parties with versions compatibility
  kubemarine.spec
  kubemarine/__main__.py
  kubemarine/procedures/config.py
  kubemarine/procedures/do.py
  test/unit/test_config.py
Labels: feature

#605 Finalized inventory loses overridden blank strings
  kubemarine/core/defaults.py
  kubemarine/core/resources.py
  kubemarine/kubernetes/__init__.py
  test/unit/test_defaults.py
Labels: bug

#555 [CPDEV-96116] - Disabling of Auto-mounting of tokens for Service accounts
  kubemarine/patches/__init__.py
  kubemarine/patches/disable_token_automount.py
  kubemarine/plugins/calico.py
  kubemarine/plugins/kubernetes_dashboard.py
  kubemarine/plugins/local_path_provisioner.py
  kubemarine/plugins/manifest.py
  kubemarine/plugins/nginx_ingress.py
  test/unit/plugins/test_nginx_ingress.py
Labels: improvement

#608 [CPDEV-98316]_Doc_need_to_update_table for_1.28.6_version_in_github
  documentation/Installation.md
Labels: documentation

#618 [CPDEV-98878] Expect calico-typha pods and deployment if enabled
  kubemarine/jinja.py
  kubemarine/resources/configurations/defaults.yaml
  test/unit/plugins/test_calico.py
Labels: improvement

#621 Procedure `do` does not work
  kubemarine/core/resources.py
  kubemarine/demo.py
  kubemarine/procedures/do.py
  test/unit/plugins/test_template.py
  test/unit/test_do.py
  test/unit/test_group.py
Labels: bug

#609 [CPREQ-8729] Improve paas_check_detected_incorrect_packages_versions_explanation
  kubemarine/procedures/check_paas.py
Labels: improvement

#603 Doc Review relating to https://github.com/Netcracker/KubeMarine/pull/596
  documentation/Installation.md
  documentation/LoadBalancing.md
Labels: documentation

#619 [CPDEV-98822] Remove default resolvConf from kubelet-config ConfigMap
  kubemarine/kubernetes/__init__.py
  kubemarine/kubernetes/components.py
  kubemarine/patches/__init__.py
  kubemarine/patches/patch_kubelet_configmap.py
Labels: bug

#624 [PSUPCLPL-14857] Change default MTU size for IPIP
  documentation/Installation.md
Labels: documentation

#623 [CPDEV-98972] Kubemarine process is stuck if remote command is stuck
  documentation/Troubleshooting.md
  kubemarine/core/errors.py
  kubemarine/core/executor.py
  kubemarine/core/group.py
  test/unit/core/test_executor.py
Labels: bug

#622 Import procedures explicitly on demand
  kubemarine.spec
  kubemarine/__main__.py
  kubemarine/procedures/__init__.py
  kubemarine/procedures/config.py
Labels: improvement

#574 [PSUPCLPL-13377] - Guide For OAuth2 authorization in Kubernetes
  documentation/internal/Hardening.md
Labels: documentation

#626 [PSUPCLPL-14914] FS mount options check
  documentation/Kubecheck.md
  kubemarine/procedures/check_iaas.py
Labels: improvement

#625 [PSUPCLPL-14914] TG update
  documentation/Troubleshooting.md
Labels: documentation

#627 [CPDEV-99413] Patch kubelet-config ConfigMap during upgrade
  kubemarine/kubernetes/__init__.py
Labels: bug
