Repository Netcracker/KubeMarine, pull requests merged in 2024-05, with the labels that each got.

#646 [CPDEV-100496] Ensure to use kubectl after wait for first control plane pods
  kubemarine/kubernetes/__init__.py
  kubemarine/procedures/upgrade.py
  test/unit/test_upgrade.py
Labels: bug

#649 [CPREQ-8730] - Feature/disable unattended upgrades
  documentation/Installation.md
  documentation/Maintenance.md
  kubemarine/packages.py
  kubemarine/patches/__init__.py
  kubemarine/patches/disable_unattended_upgrade.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/install.py
  kubemarine/resources/configurations/globals.yaml
  test/unit/test_packages.py
Labels: feature

#653 Fix unit tests on macos
  .github/workflows/ci.yaml
Labels: improvement

#657 Update ruamel.yaml dependency
  pyproject.toml
  scripts/ci/build_binary.py
Labels: improvement

#652 [PSUPCLPL-15272] IPIP connectivity check rework
  kubemarine/procedures/check_iaas.py
  kubemarine/resources/scripts/source/ipip_check/ipip_check.go
Labels: improvement

#650 [CPDEV-101596] Rework of inventory compilation
  documentation/Installation.md
  kubemarine/core/defaults.py
  kubemarine/core/errors.py
  kubemarine/core/proxytypes.py
  kubemarine/core/resources.py
  kubemarine/jinja.py
  kubemarine/plugins/__init__.py
  kubemarine/procedures/check_iaas.py
  kubemarine/resources/configurations/defaults.yaml
  test/unit/core/test_cluster.py
  test/unit/core/test_jinja.py
  test/unit/core/test_run_actions.py
  test/unit/plugins/test_template.py
  test/unit/test_coredns.py
  test/unit/test_defaults.py
  test/unit/test_k8s_cert.py
  test/unit/test_migrate_kubemarine.py
  test/unit/utils.py
Labels: bug, improvement

#656 [CPDEV-101285] Reconfigure sysctl
  documentation/Installation.md
  documentation/Maintenance.md
  kubemarine/apparmor.py
  kubemarine/core/cluster.py
  kubemarine/core/group.py
  kubemarine/core/inventory.py
  kubemarine/core/resources.py
  kubemarine/kubernetes/__init__.py
  kubemarine/procedures/install.py
  kubemarine/procedures/reconfigure.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/definitions/patch.json
  kubemarine/resources/schemas/definitions/services/kubeadm_patches.json
  kubemarine/resources/schemas/reconfigure.json
  kubemarine/selinux.py
  kubemarine/sysctl.py
  kubemarine/system.py
  test/unit/test_reconfigure.py
Labels: feature

#661 [CPDEV-101744] Update helm, python dependencies
  .github/workflows/ci.yaml
  .github/workflows/tests.yaml
  Dockerfile
  kubemarine/core/cluster.py
  kubemarine/core/schema.py
  kubemarine/core/static.py
  kubemarine/core/utils.py
  kubemarine/packages.py
  kubemarine/procedures/__init__.py
  kubemarine/procedures/backup.py
  kubemarine/resources/scripts/source/ipip_check/go.mod
  pyproject.toml
  requirements-pyinstaller.txt
  scripts/ci/build_binary.py
  scripts/ci/custom-hooks/hook-cryptography.py
  scripts/ci/install_package.py
  test/unit/plugins/test_inventory.py
Labels: improvement

#647 [CPREQ-8832] Support Kubernetes v1.30.1
  documentation/Installation.md
  kubemarine/procedures/backup.py
  kubemarine/resources/configurations/compatibility/internal/kubernetes_images.yaml
  kubemarine/resources/configurations/compatibility/internal/packages.yaml
  kubemarine/resources/configurations/compatibility/internal/plugins.yaml
  kubemarine/resources/configurations/compatibility/internal/thirdparties.yaml
  kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml
Labels: feature

#658 [CPDEV-98973] Scale Typha replicas to 1 in All-in-One
  ci/extended_cluster.yaml
  kubemarine/patches/__init__.py
  kubemarine/patches/p1_calico_typha_schedule_control_planes.py
  kubemarine/plugins/builtin.py
  kubemarine/plugins/calico.py
  kubemarine/plugins/manifest.py
  kubemarine/resources/configurations/defaults.yaml
  test/unit/plugins/test_calico.py
  test/unit/test_defaults.py
Labels: bug

#663 [CPDEV-101898] - do not create empty /etc/kubernetes/nodes-k8s-versions.txt file
  kubemarine/kubernetes/__init__.py
Labels: bug

#664 [CPDEV-101357] Remove docker support
  README.md
  documentation/Installation.md
  documentation/Kubecheck.md
  documentation/Maintenance.md
  documentation/Troubleshooting.md
  documentation/design/1-upgrade-patches-registration-and-implementation.md
  examples/cluster.yaml/full-cluster.yaml
  kubemarine/__main__.py
  kubemarine/core/defaults.py
  kubemarine/core/errors.py
  kubemarine/core/flow.py
  kubemarine/core/resources.py
  kubemarine/cri/__init__.py
  kubemarine/cri/containerd.py
  kubemarine/cri/docker.py
  kubemarine/demo.py
  kubemarine/kubernetes/__init__.py
  kubemarine/kubernetes/components.py
  kubemarine/packages.py
  kubemarine/patches/__init__.py
  kubemarine/patches/p2_reinstall_etcdctl_thirdparty.py
  kubemarine/patches/software_upgrade.yaml
  kubemarine/procedures/__init__.py
  kubemarine/procedures/backup.py
  kubemarine/procedures/check_iaas.py
  kubemarine/procedures/check_paas.py
  kubemarine/procedures/migrate_cri.py
  kubemarine/procedures/migrate_kubemarine.py
  kubemarine/procedures/restore.py
  kubemarine/procedures/upgrade.py
  kubemarine/resources/configurations/compatibility/internal/kubernetes_images.yaml
  kubemarine/resources/configurations/compatibility/internal/packages.yaml
  kubemarine/resources/configurations/compatibility/internal/plugins.yaml
  kubemarine/resources/configurations/compatibility/internal/thirdparties.yaml
  kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/configurations/globals.yaml
  kubemarine/resources/etalons/patches/software_upgrade.yaml
  kubemarine/resources/schemas/definitions/services/cri.json
  kubemarine/resources/schemas/definitions/services/packages/associations.json
  kubemarine/resources/schemas/migrate_cri.json
  kubemarine/resources/schemas/migrate_kubemarine.json
  kubemarine/resources/schemas/upgrade.json
  kubemarine/resources/scripts/etcdctl.sh
  kubemarine/thirdparties.py
  scripts/thirdparties/src/software/packages.py
  test/unit/core/test_flow.py
  test/unit/core/test_run_actions.py
  test/unit/test_cri_enrichment.py
  test/unit/test_inventory.py
  test/unit/test_migrate_cri.py
  test/unit/test_migrate_kubemarine.py
  test/unit/test_packages.py
  test/unit/test_upgrade.py
  test/unit/tools/thirdparties/test_sync.py
Labels: feature

#648 [CPDEV-100884] Validate that kubernetes images are not downgraded
  scripts/thirdparties/src/software/kubernetes_images.py
  scripts/thirdparties/src/software/packages.py
  test/unit/tools/thirdparties/stub.py
  test/unit/tools/thirdparties/test_sync.py
Labels: improvement

#659 [CPDEV-101682] Support single control plane cluster
  documentation/Troubleshooting.md
  kubemarine/core/errors.py
  kubemarine/core/resources.py
  kubemarine/kubernetes/__init__.py
  test/unit/core/test_cluster.py
  test/unit/core/test_flow.py
  test/unit/test_defaults.py
  test/unit/test_do.py
  test/unit/test_inventory.py
Labels: improvement
