Repository Netcracker/KubeMarine, pull requests merged in 2024-09, with the labels that each got.

#685 [CPDEV-101420] Fix failure of second backup after restore
  kubemarine/procedures/backup.py
Labels: bug

#676 [CPDEV-95454] Make network sub-chapter clickable
  documentation/Kubecheck.md
Labels: documentation

#686 [CPDEV-105248] - Remove 1.25 kubernetes version
  documentation/Installation.md
  kubemarine/patches/__init__.py
  kubemarine/patches/p1_pin_kubernetes_version.py
  kubemarine/resources/configurations/compatibility/internal/kubernetes_images.yaml
  kubemarine/resources/configurations/compatibility/internal/packages.yaml
  kubemarine/resources/configurations/compatibility/internal/plugins.yaml
  kubemarine/resources/configurations/compatibility/internal/thirdparties.yaml
  kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml
  kubemarine/resources/configurations/defaults.yaml
  test/unit/plugins/test_nginx_ingress.py
  test/unit/test_admission.py
  test/unit/test_defaults.py
  test/unit/test_reconfigure.py
  test/unit/test_upgrade.py
Labels: improvement

#690 [CPREQ-10003] - deprecated kuber version
  .github/workflows/integration_tests.yaml
  .github/workflows/tests.yaml
  Dockerfile
  documentation/Kubecheck.md
  kubemarine/kubernetes/__init__.py
  kubemarine/procedures/check_paas.py
  kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml
  scripts/thirdparties/src/run.py
  scripts/thirdparties/src/software/defaults.py
  scripts/thirdparties/sync.py
  test/unit/tools/thirdparties/stub.py
  test/unit/tools/thirdparties/test_sync.py
Labels: improvement

#691 [CPDEV-102270] OpenSSH server issue WA has been added to TG.
  documentation/Troubleshooting.md
Labels: documentation

#694 [CPDEV-106079] add containerd health check after restart
  kubemarine/cri/containerd.py
Labels: bug
