Repository Netcracker/KubeMarine, pull requests merged in 2024-08, with the labels that each got.

#680 [CPDEV-103936] Fix prepare_dns_etc_hosts for work with unavailable nodes
  documentation/Installation.md
  kubemarine/procedures/install.py
  kubemarine/resources/configurations/defaults.yaml
  kubemarine/resources/schemas/definitions/globals.json
Labels: bug

#682 [CPREQ-9284] k8s and 3rd party update
  documentation/Installation.md
  kubemarine/patches/software_upgrade.yaml
  kubemarine/plugins/yaml/calico-apiserver-v3.28.1-original.yaml
  kubemarine/plugins/yaml/calico-v3.28.1-original.yaml
  kubemarine/plugins/yaml/local-path-provisioner-v0.0.27-original.yaml
  kubemarine/plugins/yaml/nginx-ingress-controller-v1.11.1-original.yaml
  kubemarine/resources/configurations/compatibility/internal/kubernetes_images.yaml
  kubemarine/resources/configurations/compatibility/internal/packages.yaml
  kubemarine/resources/configurations/compatibility/internal/plugins.yaml
  kubemarine/resources/configurations/compatibility/internal/thirdparties.yaml
  kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml
  test/unit/core/test_cluster.py
  test/unit/core/test_env.py
  test/unit/core/test_flow.py
  test/unit/core/test_run_actions.py
  test/unit/plugins/test_nginx_ingress.py
  test/unit/test_upgrade.py
Labels: feature

#683 reworked version check algoritm to packaging.pypa.io
  pyproject.toml
  test/unit/plugins/test_nginx_ingress.py
Labels: bug

#681 [CPDEV-103824] - caught sftp eof error during reboot
  kubemarine/core/connections.py
Labels: bug, improvement
